name: introducao_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0 
  my_simple_package: 
  path: ./packages/my_simple_package
    # git:
    #   url: https://github.com/FelipeQueFez/introducao-dart
    #   path: ./packages/my_simple_package
    #   ref: main

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
